### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by TobiasS1402** [Ahmed-Soli/linkedin-course-downloader#1]
root@Titan:~/linkedin-course-downloader# python downloader.py
  File "downloader.py", line 25
    logging.error(f"Connection Error: {e}")
SyntaxError: invalid syntax

**Comment by Ahmed-Soli** [comment]
Problem fixed please try it again

**Comment by TobiasS1402** [comment]
I cloned it again, i still get the same issue.

**Comment by TobiasS1402** [comment]
Nevermind, i got it to work. The Linux emulation for windows doesnt work that well.
