### ISSUE TITLE
error

### ISSUE THREAD

**Issue by shadowdragon007** [Ahmed-Soli/linkedin-course-downloader#11]
C:\Users\Dragoon\Downloads\Compressed\yourscootbookingconfirmationud737k\linkedin-course-downloader-master>pip install -r requirements.txt
Requirement already satisfied: requests in c:\program files\python36\lib\site-packages (from -r requirements.txt (line 1)) (2.24.0)
Requirement already satisfied: lxml in c:\program files\python36\lib\site-packages (from -r requirements.txt (line 2)) (4.4.1)
Collecting clint
  Using cached clint-0.5.1.tar.gz (29 kB)
ERROR: Could not find a version that satisfies the requirement pickle (from -r requirements.txt (line 4)) (from versions: none)
ERROR: No matching distribution found for pickle (from -r requirements.txt (line 4))

**Comment by Ahmed-Soli** [comment]
pickle comes built in with python3 so you don't need to install it , I will remove it from the requirements file ..
