### ISSUE TITLE
Connection Error: name 'output' is not defined

### ISSUE THREAD

**Issue by percysl** [Ahmed-Soli/linkedin-course-downloader#20]
Hi man, I love your work

I think this issue is only for recently courses, I am not sure, check it out please. THank you man

**Comment by percysl** [comment]
> Hi man, I love your work
> 
> I think this issue is only for recently courses, I am not sure, check it out please. THank you man

Hi again . . .

I found the issue: LongPath in Windows 10

Thank you anyway

**Comment by Ahmed-Soli** [comment]
Glad you Figured it out .
