### ISSUE TITLE
Is there a limit on how many URL you can have?

### ISSUE THREAD

**Issue by wonderness** [Ahmed-Soli/linkedin-course-downloader#4]
About downloading the entire instructor materials, what I am trying to explain is, please see this link.

https://www.linkedin.com/learning/instructors/steve-wright

Is there a way we can come up with something that would download all the courses under him?? If its possible, what should I enter in the URL??

**Comment by wonderness** [comment]
About downloading the entire instructor materials, what I am trying to explain is, please see this link.

https://www.linkedin.com/learning/instructors/steve-wright

Is there a way we can come up with something that would download all the courses under him?? If its possible, what should I enter in the URL??

**Comment by wonderness** [comment]
Please ignore the earlier message about not downloading multiple links, I fixed the URL, it was a syntax error.

**Comment by Ahmed-Soli** [comment]
No there is not .
