### ISSUE TITLE
Error downloading video

### ISSUE THREAD

**Issue by ClementTeyssa** [Ahmed-Soli/linkedin-course-downloader#7]
Hi, thank you for your script.
I got an error during the download, some videos are download but some videos aren't download.
Do you have an idea ? 

`2020-02-07 13:42:01,094 root         INFO     [~] Writing 01 - Applications for data analysis.mp4
[################################] 15515/15515 - 00:00:01`
`2020-02-07 13:42:02,214 root         INFO     [~] Writing 01 - Applications for data analysis.srt`
`2020-02-07 13:42:02,215 root         INFO     [~] Done fetching course 'Data Science Foundations: Fundamentals' Chapter no. 7 Video no. 1`
`2020-02-07 13:42:02,215 root         INFO     [~] Fetching course 'Data Science Foundations: Fundamentals' Chapter no. 7 Video no. 2`
`2020-02-07 13:42:03,126 root         ERROR    Extracting Video URL Error , make sure you have access to linkedin learning via premium account`

**Comment by Ahmed-Soli** [comment]
@ClementTeyssa I faced the same issue when my trial premium expired , Do you still have premium access ?

**Comment by ClementTeyssa** [comment]
I think not because it's an educational account

**Comment by Ahmed-Soli** [comment]
That's the reason then .
