### ISSUE TITLE
Faild due to Too Many Requests

### ISSUE THREAD

**Issue by MagicRico** [Ahmed-Soli/linkedin-course-downloader#9]
Hi, 
I got this error after starting the script
[!] Faild due to: Too Many Requests
2020-06-08 05:31:32,815 root         INFO     [!] Faild due to: Too Many Requests
2020-06-08 05:31:32,962 root         INFO     [!] Faild due to: Too Many Requests
2020-06-08 05:31:33,141 root         INFO     [!] Faild due to: Too Many Requests

Now in my linkedin learning
Received error 429 from server for URI https://lva1-app58704.prod.linkedin.com:7220/learning-api/learningApiInit

How to solve?

**Comment by Ahmed-Soli** [comment]
The Api has limited requests per day . If it says too many requests then there is a temporary block on you account that will prevent you from accessing the API for 24 hours . Then you can use it .

**Comment by MagicRico** [comment]
> 
> 
> The Api has limited requests per day . If it says too many requests then there is a temporary block on you account that will prevent you from accessing the API for 24 hours . Then you can use it .

Thanks for your quick reply.
Do you know the maximum requests by day?

**Comment by Ahmed-Soli** [comment]
it's hard to tell as the fetching process counts and the downloading counts as well . 
Just try not to over use your account .
